version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: root
      MYSQL_USER: gongbaek
      MYSQL_PASSWORD: '1234'
      TZ: Asia/Seoul
    command:
      --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3307:3306
